name: decision-transformer-atari
channels:
- pytorch
dependencies:
- python=3.10.10
- pytorch=2.1.0+cu118
- cudatoolkit=11.8
- numpy
- psutil
- opencv
- pip
- pip:
  - atari-py
  - pyprind
  - tensorflow-gpu>=1.13
  - absl-py
  - atari-py
  - gin-config
  - gym
  - tqdm
  - blosc
  - git+https://github.com/google/dopamine.git
